apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api-production
  team: devops

commonAnnotations:
  note: This is an Production Deployment


resources:
- ns.yaml
- ../../base

    


patches:
- path: deploy-merge.yaml
  target:
    kind: Deployment
    name: public-api
- path: svc-patch.yaml
  target:
    name: svc-public-api
- path: cm-patch.yaml
  target:
    name: cm-private-api
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: public-api
    

images:
- name: KUSTOMIZE-DEFINIED
  newName: jcalderon/public
  newTag: 3.0.0
