apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

commonLabels:
  app: public-api-production
  team: devops

commonAnnotations:
  note: "This is an Production deployment"


resources:
  - ns.yaml
  - ../../base

patches:
  - target: 
      name: public-api
      kind: Deployment 
    path: deploy-merge.yaml
    
  - target:
      name: svc-public-api
    path: svc-patch.yaml

  - target:
      name: cm-private-api
    path: cm-patch.yaml

  - target:
      name: production-public-api
      kind: Ingress
    path: ingress-patch.yaml
    

images:
   - name: KUSTOMIZE-DEFINIED
     newName: jcalderon/public
     newTag: 1.0.0

