apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api-stage
  team: devops

commonAnnotations:
  note: This is an Stage deployment


resources:
- ns.yaml
- ../../base

patches:

- path: deploy-merge.yaml
  target:
    kind: Deployment
    name: public-stage-api

- path: svc-patch.yaml
  target:
    name: svc-stage-public-api

- path: cm-patch.yaml
  target:
    name: cm-private-stage-api

- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: public-stage-api 

images:
- name: KUSTOMIZE-DEFINIED
  newName: jcalderon/public
  newTag: 5.0.0
